name: Remove old artifacts

on:
  schedule:
    #Every day at lam
    - corn: '0 1 * * *'

jpbs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '3 days'